### ISSUE TITLE
有好多的bug基本无法使用变量名没有对应

### ISSUE THREAD

**Issue by yyh9488** [garsonlab/ScrollView#1]
具体的使用方法不知道有没有

**Comment by garsonlab** [comment]
新建UGUI ScrollView，替换ScrollRect组件

**Comment by yyh9488** [comment]
怎么更新item上的数据呢
![image](https://user-images.githubusercontent.com/36093955/59659722-5e727180-91d9-11e9-91a6-95700bbb13d5.png)
我赋值的原始的item

**Comment by yyh9488** [comment]
这样并没有效果

**Comment by garsonlab** [comment]
![use](https://user-images.githubusercontent.com/13958934/59662882-6aadfd00-91e0-11e9-9b9a-1a69e065bac4.png)

**Comment by yyh9488** [comment]
![image](https://user-images.githubusercontent.com/36093955/59663868-8b775200-91e2-11e9-89cb-e23eaa914fb0.png)
数据的更新好像不对，中间的对齐视乎也不太正确，不知道是不是我使用的问题
你上传的这个版本似乎有很多的问题我修改过ScrollViewEditor.cs中的onRenderItem变量名

**Comment by yyh9488** [comment]
![image](https://user-images.githubusercontent.com/36093955/59664225-37b93880-91e3-11e9-9fe7-4d1da898185c.png)

**Comment by garsonlab** [comment]
onRenderItem已修复，增加了栗子
