### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by ndsl95** [garsonlab/ScrollView#2]
无法使用，2018.4.1f1挂上去后，Content和Prefab一直报错，而且也无法手动指定。

**Comment by ndsl95** [comment]
根据上一条Issus的操作方法，无效果，挂上了Scrollview.cs脚本，报错。
然后删除ScrollRect还是报错。

**Comment by garsonlab** [comment]
变量名忘记修改了，已修复，可以看刚上传的栗子
